### ISSUE TITLE
How do I just add links?

### ISSUE THREAD

**Issue by KUPOkinz** [zach-morris/argdb_scraper#1]
Using the info I shown before, I just want to add links to my google drive. I don't care about images, pictures, hash-checks, etc, I just want the name of the system and the name of the rom. Is this the thing I need to use in order to do that?

**Comment by zach-morris** [comment]
See [example 1](https://github.com/zach-morris/argdb_scraper#1--simplest-example--a-list-of-three-games-with-no-metadata).  This is as simple as it gets for this particular tool.

**Comment by KUPOkinz** [comment]
Thank you Zach, I am looking at it now. It's a huge jumble and I have no idea where to begin, but I am following it carefully. Thank you so much. Do you have discord or any form of way for us to momentarily chat?

**Comment by zach-morris** [comment]
Yes, i mean it's a bit of a learning curve just starting with python to start with this, but as far as languages go I think it's the easiest to pick up.  I didn't know python before starting IAGL and that was what I used to learn it (and I'm still not really very good at it).

You'll probably want to look at lists and dicts.  The dict that this scraper dumps out contains all the data.  If you're just starting with python I'd suggest an IDE to help you look at the data with a GUI (like pycharm, spyder, etc).

**Comment by KUPOkinz** [comment]
Okay thank you for keep responding Zach, it really does mean a lot too me that you're helping me. I have downloaded the zip from your github with the resources and stuff and I've read the readme atleast 10 times, I just don't know where to begin with any of this. I have installed Python 3.7 into my windows systems, but from there I'm lost. I don't know what to do now :P Again, do you got a discord and thank you :)

**Comment by KUPOkinz** [comment]
Okay, I got you Example form to open up in PyCharm :) Now, lost again :P

**Comment by zach-morris** [comment]
To run the example:
```
python "/path_to/simple_example1.py"
```
Will kick out the same exact xml file in the output directory.  If you change the files list in simple_example1.py, or say the output_settings and run the command again, you'll see the xml output change to the files you listed.

**Comment by KUPOkinz** [comment]
So I have opened exmaple in PyCharm, I see this part in the script 

#Here's my 3 files
files = ['https://drive.google.com/uc?export=download&id=11-S0be1FQqV_Lvn0e3st9AUtvimStZDg&name=/2048.nes',
		'https://drive.google.com/uc?export=download&id=1lvwzcqBCrm4ODPEY9P6ih03uN7SyAiDe&name=/BladeBuster.nes',
		'https://drive.google.com/uc?export=download&id=13_QczPj-5faspIj_kB2nNW8BUtE7yBP7&name=/dpadhero2.nes']

If I just and only just want the links/game name, do I just add my google links into this and then try to run the file to export the example like it did with the nes?

**Comment by zach-morris** [comment]
You can run it in pycharm by following [this](https://www.jetbrains.com/help/pycharm/creating-and-running-your-first-python-project.html)

And yes, if you change that list, then rerun it, the result will change.  The game name listed in the xml is based on the filename at the end of that url, and then the tool just kicks that url into the xml file for the game file url

**Comment by KUPOkinz** [comment]
Zach thank you so much for taking time to help me, one sec I will try it.

**Comment by KUPOkinz** [comment]
I tried to open it in PyCharm, and it opened your README thats wrote on this page itself.

**Comment by KUPOkinz** [comment]
I'm going to do it the way before it seems easier to just make a copy of the example file and edit the copy, then try to run it. How do I actually run the file? 

It would be this right? Python is installd in my CMD and I renamed the folder to Scraper and placed in Root of C:/ for easier access. 

CMD
Python
Python "/C:/Scraper/simple_example1.py"

Correct?

**Comment by KUPOkinz** [comment]
I get an invalid centax when trying to run the example.py file.

**Comment by zach-morris** [comment]
yes, you can run it directly in python as well from the command line.   However, I'm guessing you didn't install anything else besides python.  Take a look at the [requirements](https://github.com/zach-morris/argdb_scraper#requirements) listed too.  Python's strong suit is code modules and importing them into different projects.

```
Example:
>python --version
Python 3.7.1
>python "C:/Scraper/simple_example1.py"
without the modules, you'll get some kind of import error

You need to download various modules I've installed in my python environment.  To do that you need a package manager like pip or anaconda.  pip is easiest:

Install pip
```
>python -m pip install -U pip

>pip help
#should return something
```

Now you can install the requirements.  Example (I think this will install all of them):
```
pip install fuzzywuzzy, html2text, dateutil, lxml
```

**Comment by KUPOkinz** [comment]
Okay one moment, thank you :)

**Comment by KUPOkinz** [comment]
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> >python -m pip install -U pip
  File "<stdin>", line 1
    >>> >python -m pip install -U pip
    ^
SyntaxError: invalid syntax
>>>   File "<stdin>", line 1
  File "<stdin>", line 1
    File "<stdin>", line 1
    ^
IndentationError: unexpected indent
>>>     >python -m pip install -U pip
  File "<stdin>", line 1
    >python -m pip install -U pip
    ^
IndentationError: unexpected indent
>>>     ^
  File "<stdin>", line 1
    ^
    ^
IndentationError: unexpected indent
>>> SyntaxError: invalid syntax
  File "<stdin>", line 1
    SyntaxError: invalid syntax
                         ^
SyntaxError: invalid syntax
>>> >>>

**Comment by KUPOkinz** [comment]
I get the same syntex error when typing this into python.

**Comment by zach-morris** [comment]
Your in the python command prompt, run it directly in the windows cmd window

**Comment by KUPOkinz** [comment]
Okay!

**Comment by zach-morris** [comment]
I'm off to bed.  Good luck.

**Comment by KUPOkinz** [comment]
Microsoft Windows [Version 10.0.19041.113]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\KUPOkinz>>python -m pip install -U pip
'-m' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\KUPOkinz>

**Comment by KUPOkinz** [comment]
Waaait, please :P Kast thing, this is what I receive when typing into CMD :P

**Comment by KUPOkinz** [comment]
Oh! 

>python "C:/Scraper/simple_example1.py"

Opened up PyCharm when typed into CMD

**Comment by KUPOkinz** [comment]
I will edit the rest of my progress here, Goodnight and thank you! 

I managed to get the packages installed, turns out PIP was already installed when I got Python earlier :)

**Comment by KUPOkinz** [comment]
I've asked my friend who is very familiar with Python (they remotePC'ed my computer and was gonna do this for me) and can confirm, they say you are missing the Lib folder from your git page, which is why I could not get past that error last night as they ended up running into the same issue I did, albeit it took them 2 minutes to get there instead of the 3 hours it took me lol.

**Comment by KUPOkinz** [comment]
Zach are you around today buddy? I do believe the lib folder if I am understanding everything correctly, is what I am missing :)

**Comment by zach-morris** [comment]
Yeah, that was my bad.  Hopefully you can get it to work now
