### ISSUE TITLE
ModuleNotFoundError: No module named 'resources.lib'

### ISSUE THREAD

**Issue by KUPOkinz** [zach-morris/argdb_scraper#2]
C:\Users\KUPOkinz>python "C:/Scraper/simple_example1.py"
Traceback (most recent call last):
File "C:/Scraper/simple_example1.py", line 3, in
from resources.lib.argdb_scraper import *
ModuleNotFoundError: No module named 'resources.lib'

I'm not sure if you get notifications on closed topics and this seems to be a different issue, so I'm opening it as a new issue. If I'm understanding this correctly, I believe your download is missing the above files and cannot proceed farther than this.

**Comment by KUPOkinz** [comment]
Are you able to upload the rest of this file Zach?

**Comment by zach-morris** [comment]
Yeah, sorry about that.  Not sure why it didn't get pushed initially.  I've updated the repo you can re-clone it and it should have the files needed

I also added a requirements.txt folder for everything needed to import
