### ISSUE TITLE
What format is your google links? 

### ISSUE THREAD

**Issue by KUPOkinz** [zach-morris/argdb_scraper#3]
Cannot find the correct way to parse my google link, in which way have you grabbed these link files? I've noticed there is serveral different formats to a shared drive link.  We're getting so close :( 

Mine look like this
Addams Family, The (Europe) (En,Fr,De).nes https://drive.google.com/uc?id=18uZ7wqnlLn5VrBb891dOi-3pfUIUiONG&export=download
Maxi 15 (USA) (Rev 1) (Unl).nes https://drive.google.com/uc?id=1J1Zcz7Wm7y_PgDaXds10_hj5N7bqwYWG&export=download
8 Eyes (USA).nes https://drive.google.com/uc?id=1DHB2ORF9S2J92s0bfnDvIpNp7-zPr3dz&export=download
Action in New York (Europe).nes https://drive.google.com/uc?id=1bFs8iIR710N-8vBzW0mCEoKQR-yURaOl&export=download
Aces - Iron Eagle 3 (Japan).nes https://drive.google.com/uc?id=1P1exKfAg9leX7b3CYIj-CyFSBp-MC7G8&export=download
A Ressha de Ikou (Japan).nes https://drive.google.com/uc?id=1PI3dKI2UPdVh8dWrf012wlob01jE69x9&export=download
Abarenbou Tengu (Japan).nes https://drive.google.com/uc?id=1xHqYhA3xFXOEtJC1d_SfbGqcxBoTT6Wa&export=download

And what method are you using the past the game name at the /end of the link?

Also, the 3 default game links that are exported form the example.py, do not work in IAGL and reportback with Error, check log.

**Comment by zach-morris** [comment]
Try one of your links [here](https://sites.google.com/site/gdocs2direct/).  You'll probably find that the returned URL will look like the ones in the example list where but parsing FOO out of:
```
https://drive.google.com/uc?id=FOO&export=download
```
You should be able to generate a similiar looking link quite easily with python and your links and filenames above

**Comment by zach-morris** [comment]
I've updated the IAGL readme to add some more discussion places.  [Discord](https://discord.gg/x74tJC) being one of the ways.

**Comment by KUPOkinz** [comment]
> I've updated the IAGL readme to add some more discussion places. [Discord](https://discord.gg/x74tJC) being one of the ways.

Thank you :)

**Comment by KUPOkinz** [comment]
> I've updated the IAGL readme to add some more discussion places. [Discord](https://discord.gg/x74tJC) being one of the ways.

Can you come to your discord lol? Ty <3 This will make things so much easier!

**Comment by zach-morris** [comment]
Example 1 is updated, but more examples maybe can help you with your issue.  I'm on discord now
