### ISSUE TITLE
Unable to play the game

### ISSUE THREAD

**Issue by nubonics** [zach-morris/argdb_scraper#4]
> 2020-04-10 07:20:52.158 T:15704  NOTICE: -----------------------------------------------------------------------
> 2020-04-10 07:20:52.158 T:15704  NOTICE: Starting Kodi (18.6 Git:20200229-8e967df921). Platform: Windows NT x86 64-bit
> 2020-04-10 07:20:52.158 T:15704  NOTICE: Using Release Kodi x64 build
> 2020-04-10 07:20:52.158 T:15704  NOTICE: Kodi compiled 2020-02-29 by MSVC 191627034 for Windows NT x86 64-bit version 10.0 (0x0A000006)
> 2020-04-10 07:20:52.158 T:15704  NOTICE: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.18362
> 2020-04-10 07:20:52.158 T:15704  NOTICE: FFmpeg version/source: 4.0.4-Kodi
> 2020-04-10 07:20:52.158 T:15704  NOTICE: Host CPU: AMD Ryzen 5 3600 6-Core Processor, 12 cores available
> 2020-04-10 07:20:52.158 T:15704  NOTICE: Desktop Resolution: 1920x1080 32Bit at 60Hz
> 2020-04-10 07:20:52.158 T:15704  NOTICE: Running with restricted rights
> 2020-04-10 07:20:52.158 T:15704  NOTICE: Aero is enabled
> 2020-04-10 07:20:52.158 T:15704  NOTICE: special://xbmc/ is mapped to: C:\Users\Nubonix\Desktop\Kodi
> 2020-04-10 07:20:52.158 T:15704  NOTICE: special://xbmcbin/ is mapped to: C:\Users\Nubonix\Desktop\Kodi
> 2020-04-10 07:20:52.158 T:15704  NOTICE: special://xbmcbinaddons/ is mapped to: C:\Users\Nubonix\Desktop\Kodi/addons
> 2020-04-10 07:20:52.158 T:15704  NOTICE: special://masterprofile/ is mapped to: C:\Users\Nubonix\Desktop\Kodi\portable_data\userdata
> 2020-04-10 07:20:52.158 T:15704  NOTICE: special://home/ is mapped to: C:\Users\Nubonix\Desktop\Kodi\portable_data\
> 2020-04-10 07:20:52.158 T:15704  NOTICE: special://temp/ is mapped to: C:\Users\Nubonix\Desktop\Kodi\portable_data\cache
> 2020-04-10 07:20:52.158 T:15704  NOTICE: special://logpath/ is mapped to: C:\Users\Nubonix\Desktop\Kodi\portable_data\
> 2020-04-10 07:20:52.158 T:15704  NOTICE: The executable running is: C:\Users\Nubonix\Desktop\Kodi\kodi.exe
> 2020-04-10 07:20:52.205 T:15704  NOTICE: Local hostname: MAIN-DESKTOP
> 2020-04-10 07:20:52.205 T:15704  NOTICE: Log File is located: C:\Users\Nubonix\Desktop\Kodi\portable_data\kodi.log
> 2020-04-10 07:20:52.205 T:15704  NOTICE: -----------------------------------------------------------------------
> 2020-04-10 07:20:52.206 T:15704    INFO: loading settings
> 2020-04-10 07:20:52.207 T:15704  NOTICE: special://profile/ is mapped to: special://masterprofile/
> 2020-04-10 07:20:52.212 T:15704   DEBUG: CSkinSettings: no <skinsettings> tag found
> 2020-04-10 07:20:52.212 T:15704  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
> 2020-04-10 07:20:52.212 T:15704  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
> 2020-04-10 07:20:52.212 T:15704  NOTICE: Default Video Player: VideoPlayer
> 2020-04-10 07:20:52.212 T:15704  NOTICE: Default Audio Player: paplayer
> 2020-04-10 07:20:52.212 T:15704  NOTICE: Disabled debug logging due to GUI setting. Level 0.
> 2020-04-10 07:20:52.212 T:15704  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
> 2020-04-10 07:20:52.216 T:15704  NOTICE: Running database version Addons27
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: audioencoder.kodi.builtin.aac v1.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: audioencoder.kodi.builtin.wma v1.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: game.controller.default v1.0.8 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: game.controller.snes v1.0.8 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.global.audioengine v1.0.1 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.global.filesystem v1.0.2 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.global.general v1.0.3 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.global.gui v5.12.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.global.main v1.0.14 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.global.network v1.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.audiodecoder v2.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.audioencoder v2.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.game v1.1.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.imagedecoder v2.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.inputstream v2.0.8 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.peripheral v1.3.7 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.pvr v5.10.3 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.screensaver v2.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.vfs v2.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.videocodec v1.0.1 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.binary.instance.visualization v2.0.1 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: kodi.resource v1.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.album.universal v3.1.2 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.artists.universal v4.3.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.common.allmusic.com v3.2.1 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.common.fanart.tv v3.6.2 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.common.imdb.com v3.1.5 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.common.musicbrainz.org v2.2.1 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.common.theaudiodb.com v2.0.3 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.common.themoviedb.org v3.1.10 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.local v1.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.themoviedb.org v5.1.10 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: metadata.tvshows.themoviedb.org v3.5.2 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: peripheral.joystick v1.4.9 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: plugin.program.iagl v2.1.6 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: plugin.video.youtube v6.7.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: repository.xbmc.org v3.1.6 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: resource.images.weathericons.default v1.1.8 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: resource.language.en_gb v2.0.1 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: resource.uisounds.kodi v1.0.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: screensaver.xbmc.builtin.black v1.0.33 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: screensaver.xbmc.builtin.dim v1.0.59 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.certifi v2019.9.11 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.chardet v3.0.4 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.dateutil v2.8.1 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.elementtree v1.2.8 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.idna v2.8 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.kodi-six v0.1.3 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.pil v1.1.7 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.pycryptodome v3.4.3 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.requests v2.22.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.routing v0.2.3 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.six v1.13.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: script.module.urllib3 v1.25.6 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: service.xbmc.versioncheck v0.5.4 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: skin.estouchy v2.0.28 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: skin.estuary v2.0.27 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: webinterface.default v18.x-2.4.6 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: xbmc.addon v18.6.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: xbmc.core v0.1.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: xbmc.gui v5.14.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: xbmc.json v10.3.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: xbmc.metadata v2.1.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: xbmc.python v2.26.0 installed
> 2020-04-10 07:20:52.228 T:15704  NOTICE: ADDON: xbmc.webinterface v1.0.0 installed
> 2020-04-10 07:20:52.271 T:20592  NOTICE: Found 2 Lists of Devices
> 2020-04-10 07:20:52.271 T:20592  NOTICE: Enumerated DIRECTSOUND devices:
> 2020-04-10 07:20:52.271 T:20592  NOTICE:     Device 1
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_deviceName      : {D6811EE4-8EAB-4773-A296-83183DC0B855}
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_displayName     : SPDIF - Digital Audio (S/PDIF) (High Definition Audio Device)
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_displayNameExtra: DIRECTSOUND: Digital Audio (S/PDIF) (High Definition Audio Device)
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_channels        : FL, FR
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_sampleRates     : 48000
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_RAW
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512
> 2020-04-10 07:20:52.271 T:20592  NOTICE:     Device 2
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_deviceName      : default
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_displayName     : default
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_displayNameExtra:
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_channels        : FL, FR
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_sampleRates     : 48000
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_RAW
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512
> 2020-04-10 07:20:52.271 T:20592  NOTICE: Enumerated WASAPI devices:
> 2020-04-10 07:20:52.271 T:20592  NOTICE:     Device 1
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_deviceName      : {D6811EE4-8EAB-4773-A296-83183DC0B855}
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_displayName     : SPDIF - Digital Audio (S/PDIF) (High Definition Audio Device)
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_displayNameExtra: WASAPI: Digital Audio (S/PDIF) (High Definition Audio Device)
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_channels        : FL, FR
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_sampleRates     : 192000,96000,88200,48000,44100,32000
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_RAW
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_streamTypes     : STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_512,STREAM_TYPE_AC3
> 2020-04-10 07:20:52.271 T:20592  NOTICE:     Device 2
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_deviceName      : default
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_displayName     : default
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_displayNameExtra:
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_channels        : FL, FR
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_sampleRates     : 192000,96000,88200,48000,44100,32000
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_RAW
> 2020-04-10 07:20:52.271 T:20592  NOTICE:         m_streamTypes     : STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_512,STREAM_TYPE_AC3
> 2020-04-10 07:20:52.312 T:15704  NOTICE: Primary mode: Generic PnP Monitor #1: 1920x1080 @ 60.00Hz
> 2020-04-10 07:20:52.312 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 640x480 @ 59.94Hz
> 2020-04-10 07:20:52.313 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 640x480 @ 60.00Hz
> 2020-04-10 07:20:52.313 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 640x480 @ 72.00Hz
> 2020-04-10 07:20:52.313 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 640x480 @ 75.00Hz
> 2020-04-10 07:20:52.313 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 720x480 @ 60.00Hz
> 2020-04-10 07:20:52.313 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 720x480 @ 59.94Hz
> 2020-04-10 07:20:52.313 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 720x576 @ 50.00Hz
> 2020-04-10 07:20:52.313 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 800x600 @ 56.00Hz
> 2020-04-10 07:20:52.314 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 800x600 @ 60.00Hz
> 2020-04-10 07:20:52.314 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 800x600 @ 72.00Hz
> 2020-04-10 07:20:52.314 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 800x600 @ 75.00Hz
> 2020-04-10 07:20:52.314 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1024x768 @ 60.00Hz
> 2020-04-10 07:20:52.314 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1024x768 @ 70.00Hz
> 2020-04-10 07:20:52.314 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1024x768 @ 75.00Hz
> 2020-04-10 07:20:52.314 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1152x864 @ 75.00Hz
> 2020-04-10 07:20:52.315 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1176x664 @ 50.00Hz
> 2020-04-10 07:20:52.315 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1176x664 @ 60.00Hz
> 2020-04-10 07:20:52.315 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1176x664 @ 59.94Hz
> 2020-04-10 07:20:52.316 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1280x720 @ 60.00Hz
> 2020-04-10 07:20:52.316 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1280x720 @ 59.94Hz
> 2020-04-10 07:20:52.316 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1280x720 @ 50.00Hz
> 2020-04-10 07:20:52.317 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1280x768 @ 60.00Hz
> 2020-04-10 07:20:52.317 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1280x800 @ 60.00Hz
> 2020-04-10 07:20:52.317 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1280x960 @ 60.00Hz
> 2020-04-10 07:20:52.318 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1280x1024 @ 60.00Hz
> 2020-04-10 07:20:52.318 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1280x1024 @ 75.00Hz
> 2020-04-10 07:20:52.318 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1360x768 @ 60.00Hz
> 2020-04-10 07:20:52.319 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1366x768 @ 60.00Hz
> 2020-04-10 07:20:52.319 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1600x900 @ 59.94Hz
> 2020-04-10 07:20:52.319 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1600x900 @ 60.00Hz
> 2020-04-10 07:20:52.320 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1600x1024 @ 59.94Hz
> 2020-04-10 07:20:52.320 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1600x1024 @ 60.00Hz
> 2020-04-10 07:20:52.321 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1600x1200 @ 60.00Hz
> 2020-04-10 07:20:52.321 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1680x1050 @ 59.94Hz
> 2020-04-10 07:20:52.321 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1680x1050 @ 60.00Hz
> 2020-04-10 07:20:52.321 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1920x1080 @ 60.00Hz
> 2020-04-10 07:20:52.321 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1920x1080 @ 59.94Hz
> 2020-04-10 07:20:52.321 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1920x1080 @ 50.00Hz
> 2020-04-10 07:20:52.322 T:15704  NOTICE: Additional mode: Generic PnP Monitor #1: 1440x900 @ 60.00Hz
> 2020-04-10 07:20:52.322 T:15704  NOTICE: Checking resolution 16
> 2020-04-10 07:20:52.571 T:29548  NOTICE: Running database version Addons27
> 2020-04-10 07:20:52.571 T:29548  NOTICE: Running database version ViewModes6
> 2020-04-10 07:20:52.572 T:29548  NOTICE: Running database version Textures13
> 2020-04-10 07:20:52.573 T:29548  NOTICE: Running database version MyMusic72
> 2020-04-10 07:20:52.575 T:29548  NOTICE: Running database version MyVideos116
> 2020-04-10 07:20:52.575 T:29548  NOTICE: Running database version TV32
> 2020-04-10 07:20:52.576 T:29548  NOTICE: Running database version Epg12
> 2020-04-10 07:20:52.594 T:15704  NOTICE:   load skin from: C:\Users\Nubonix\Desktop\Kodi\addons\skin.estuary (version: 2.0.27)
> 2020-04-10 07:20:52.699 T:15704 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
> 2020-04-10 07:20:52.710 T:15704  NOTICE: PERIPHERALS::CPeripheralBus::Register - new keyboard device registered on application->keyboard: Keyboard (0000:0000)
> 2020-04-10 07:20:52.710 T:15704  NOTICE: PERIPHERALS::CPeripheralBus::Register - new mouse device registered on application->mouse: Mouse (0000:0000)
> 2020-04-10 07:20:52.711 T:15704  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
> 2020-04-10 07:20:52.711 T:15704  NOTICE: Loaded playercorefactory configuration
> 2020-04-10 07:20:52.712 T:15704  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
> 2020-04-10 07:20:52.712 T:15704  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
> 2020-04-10 07:20:52.716 T:15704  NOTICE: initialize done
> 2020-04-10 07:20:52.716 T:15704  NOTICE: Running the application...
> 2020-04-10 07:20:52.716 T:24552  NOTICE: ES: Starting UDP Event server on port 9777
> 2020-04-10 07:20:52.717 T:24552  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
> 2020-04-10 07:20:54.459 T:3688  NOTICE: IAGL:  Lets Play!
> 2020-04-10 07:20:57.157 T:26504  NOTICE: Previous line repeats 2 times.
> 2020-04-10 07:20:57.157 T:26504   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.iagl/game/NES_PD_GAMES/2048
> 2020-04-10 07:20:57.157 T:27108   ERROR: NEWADDON Invalid Date Format ""
> 2020-04-10 07:20:57.164 T:27108   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.KeyError'>
>                                             Error Contents: '@size'
>                                             Traceback (most recent call last):
>                                               File "C:\Users\Nubonix\Desktop\Kodi\portable_data\addons\plugin.program.iagl\addon.py", line 1392, in <module>
>                                                 plugin.run(sys.argv)
>                                               File "C:\Users\Nubonix\Desktop\Kodi\portable_data\addons\script.module.routing\lib\routing.py", line 130, in run
>                                                 self._dispatch(self.path)
>                                               File "C:\Users\Nubonix\Desktop\Kodi\portable_data\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
>                                                 view_func(**kwargs)
>                                               File "C:\Users\Nubonix\Desktop\Kodi\portable_data\addons\plugin.program.iagl\addon.py", line 476, in get_game
>                                                 IAGL_DL = iagl_download(current_game['json']) #Initialize download object
>                                               File "C:\Users\Nubonix\Desktop\Kodi\portable_data\addons\plugin.program.iagl\resources\lib\main.py", line 3262, in __init__
>                                                 self.current_estimated_file_sizes = [self.json['game']['rom']['@size']]
>                                             KeyError: '@size'
>                                             -->End of Python script error report<--
> 2020-04-10 07:20:57.173 T:15704   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.iagl/game/NES_PD_GAMES/2048) failed
> 2020-04-10 07:20:57.237 T:5556  NOTICE: IAGL:  Lets Play!
> 2020-04-10 07:20:59.619 T:15704  NOTICE: Stopping player
> 2020-04-10 07:20:59.619 T:15704  NOTICE: Storing total System Uptime
> 2020-04-10 07:20:59.619 T:15704  NOTICE: Saving settings
> 2020-04-10 07:20:59.628 T:15704  NOTICE: Saving skin settings
> 2020-04-10 07:20:59.633 T:15704  NOTICE: Stopping all
> 2020-04-10 07:20:59.633 T:15704  NOTICE: ES: Stopping event server
> 2020-04-10 07:20:59.721 T:24552  NOTICE: ES: UDP Event server stopped
> 2020-04-10 07:20:59.738 T:15704  NOTICE: Application stopped
> 2020-04-10 07:20:59.939 T:15704  NOTICE: XBApplicationEx: destroying...
> 2020-04-10 07:21:00.217 T:15704  NOTICE: unload skin
> 2020-04-10 07:21:00.254 T:15704  NOTICE: unload sections
> 2020-04-10 07:21:02.269 T:15704  NOTICE: XBApplicationEx: application stopped!

Hi, was hoping you could help me get this to work... Have been trying for awhile, and I can't seem to get the game in a playable state.

I have been able to install kodi, install iagl, dl&clone this repo, run it to create the NES xml file via the simple_example1.py and save it to the dat directory in kodi, however, I get this error when I attempt to download the game. The download seems to work via my browser (removing a few variables), however, I'm assuming that the browser != kodi/iagl

Please note: I am a fairly experienced python developer myself... however, I am now at a standstill on where to go from here...

Your help would be much appreciated!
Thank you in advance!

**Comment by zach-morris** [comment]
Hmm.  yeah i didn't actually try my example.  I'll take a look and update it accordingly (also working on some better examples and cleaning up the readme).  It looks like the example was just a little too simple and IAGL is complaining about file size missing.

**Comment by nubonics** [comment]
ohhhh okay, hmm, would make sense i suppose, as i have basically tried every combination under the son as far as the download url. Well, alright, & once again, really appreciate you doing this. Will be awaiting your push!

**Comment by zach-morris** [comment]
Example 1 is fixed some more examples coming
